### ISSUE TITLE
[CI] CodeCov no longer works after upgrade to v4 of the action

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/flow-framework#490]
### What is the bug?

#484 upgraded our codecov GitHub Action dependency from v3 to v4.   One of the listed [Breaking Changes](https://github.com/codecov/codecov-action/releases/tag/v4.0.0) is:
> Tokenless uploading is unsupported. However, PRs made from forks to the upstream public repos will support tokenless (e.g. contributors to OS projects do not need the upstream repo's Codecov token). This [doc](https://docs.codecov.com/docs/adding-the-codecov-token#github-actions) shows instructions on how to add the Codecov token.

This results in failures in our CI workflow:

> ==> Running command '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov create-commit'
> /home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov create-commit -C 634e8d8b252eb6b417485148d167598f91a38dc0
> ==> Uploader SHASUM verified (103bfefcc56f76473179e600b96eb8150b0f349ad94836b0f63f03ffac469ad7  codecov)
> info - 2024-02-04 00:[27](https://github.com/opensearch-project/flow-framework/actions/runs/7770351696/job/21191211253#step:5:28):18,396 -- ci service found: github-actions
> Error: Codecov token not found. Please provide Codecov token with -t flag.
> Warning: Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1

### How can one reproduce the bug?

1. Submit a PR.
2. Observe lack of a code coverage comment.

### What is the expected behavior?

Code coverage, as established org-wide, see https://github.com/opensearch-project/opensearch-plugins/issues/46 and related issues.

### What is your host/environment?

GitHub Actions

### Do you have any additional context?

The [resolution instructions at the CodeCov repo](https://docs.codecov.com/docs/adding-the-codecov-token#github-actions) indicate adding an appropriate Secret to the repo will resolve this.  We would add a `token:` field under the `with:` here [referencing that secret](https://github.com/codecov/codecov-action?tab=readme-ov-file#usage):
```yaml
      - name: Upload Coverage Report
        if: ${{ matrix.codecov }}
        uses: codecov/codecov-action@v4
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
```
However, individual repo maintainers do not have permissions to edit secrets, so resolving this will require EE team to add the secrets both here and org-wide.

I did experiment on my fork (which, as a fork, the docs say could have used the upstream public repo's token) with the standard-named token, but it doesn't seem to be present, so needs to be added.
```yaml
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.CODECOV_TOKEN }}
```

CC @bbarani
